name: "Test docker-compose"
on:
  push:
    branches:
      - "**"
jobs:
  test_core:
    strategy:
      matrix:
        directory: ["docker-compose/camunda-8.4"]
        compose:
          - compose_args: "-f docker-compose-core.yaml"
            run_e2e_tests: false
          - compose_args: "-f docker-compose.yaml"
            run_e2e_tests: false
    name: Testing for ${{ matrix.compose.compose_args }}
    uses: ./.github/workflows/template-deploy.yaml
    secrets: inherit
    with:
      compose_args: ${{ matrix.compose.compose_args }}
      run_e2e_tests: ${{ matrix.compose.run_e2e_tests }}
      directory: ${{ matrix.directory }}
